/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kongqw_serialportlibrary_SerialPort */

#ifndef _Included_com_kongqw_serialportlibrary_SerialPort
#define _Included_com_kongqw_serialportlibrary_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kongqw_serialportlibrary_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_kongqw_serialportlibrary_SerialPort_open
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_kongqw_serialportlibrary_SerialPort
 * Method:    open2
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_kongqw_serialportlibrary_SerialPort_open2
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_kongqw_serialportlibrary_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kongqw_serialportlibrary_SerialPort_close
  (JNIEnv * env, jobject){
  };


#ifdef __cplusplus
}
#endif
#endif
